import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContainerWrapper from "./components/ContainerWrapper";
import Navbar from "./components/portfolio/Navbar";
import Footer from "./components/portfolio/Footer";
import WhatsAppButton from "./components/ui/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContainerWrapper>
          <Navbar />
        </ContainerWrapper>
        {children}
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
